notifications:
  email:
    on_success: never
    on_failure: change
language: csharp
mono: none
dist: xenial
dotnet: 3.1
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test xamarinExample.Test/xamarinExample.Test.csproj
